org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.228
# The loader version range can only use the major version of FML as bounds
loader_version_range=[1,)

mod_id=yes_corpse_model
mod_name=Yes! Corpse Model
mod_license=MIT License
mod_version=1.0.0-ysm2.6.5
mod_group_id=io.github.createmeow.ysm_corpse
